dcs-config: 
  PAYLOAD_DIR: "/apps/dcs/data/biz"
  KAFKA_HOST: "kafka-mq.han.gg:9092"
  CA_PATH: "/apps/dcs/data/certs/ca.pem"
  CERT_PATH: "/apps/dcs/data/certs/han.gg.crt"
  KEY_PATH: "/apps/dcs/data/certs/han.gg.key"
  KAFKA_FLIGHT_TOPIC: "rts_flights_topic"
  KAFKA_PASSENGER_TOPIC: "rts_passengers_topic"
  KAFKA_RTS_PF_CG_ID: "rts_passenger_flights_consumer"
  log_directory: "/apps/dcs/data/logs"
  log_level: "INFO"
  sampled_flights_no: 10
  sampled_passengers_no: 300
  PASSENGER_DL_INTERVAL: 30.0
  RMQ_HOST: "rabbit-server.han.gg"
  RMQ_PORT: 5671
  RMQ_FLIGHT_QUEUE: "rts_flights_queue"
  RMQ_PASSENGER_QUEUE: "rts_passengers_queue"
  RMQ_POLL_INT: 5.0
  MYSQL_HOST: "db1.han.gg"
  MYSQL_PORT: 3306
  MYSQL_DB: "dcs"
  RMQ_SCHED_PF_QUEUE: "sched_pf_queue"
  IBM_MQ_HOST: "ibmmq.han.gg"
  IBM_MQ_PORT: 1414
  IBM_MQ_QUEUE_MANAGER: "DADDYQM"
  IBM_MQ_CHANNEL: "DEV.APP.SVRCONN"
  IBM_MQ_KEY_REPO: "/apps/dcs/data/certs/ibmmq_client/client"
  RMQ_SCHED_PF_QUEUE: "sched_pf_queue"
  IBM_MQ_QUEUE_NAME: "PF.TOKEN.QUEUE"
  PF_BE_HOST: "pf-be.han.gg"
  SCHEDULER_INTERVAL: 600
  KAFKA_DATA_LAKE_TOPIC: "pf_data_lake_topic"
