apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-gen
  labels:
    app: token-gen
    appCode: dcs
spec:
  replicas: {{ .Values.global.replicas.token_gen }}
  selector:
    matchLabels:
      app: token-gen
      appCode: dcs
  template:
    metadata:
      labels:
        app: token-gen
        appCode: dcs
    spec:
      containers:
      - name: token-gen
        image: {{ .Values.global.image.repository }}_{{ .Values.image.tag1 }}:{{ .Values.image.tag2 }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ .Values.global.env.configmap }}
        - secretRef:
            name: {{ .Values.global.env.secret }}
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        volumeMounts:
        - name: {{ .Values.global.volumes.name }}
          mountPath: {{ .Values.global.volumes.mountPath }}
      volumes:
      - name: {{ .Values.global.volumes.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.global.volumes.pvc }}
