apiVersion: apps/v1
kind: Deployment
metadata:
  name: satellite1
  labels:
    app: satellite1
    appCode: load-generator
spec:
  replicas: {{ .Values.satellite1.replicas }}
  selector:
    matchLabels:
      app: satellite1
      appCode: load-generator
  template:
    metadata:
      labels:
        app: satellite1
        appCode: load-generator
    spec:
      containers:
      - name: satellite1
        image: {{ .Values.global.image.repository }}:{{ .Values.satellite1.image.tag }}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: loadgen-config
        - secretRef:
            name: loadgen-secret
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        volumeMounts:
        - name: load-gen-data
          mountPath: /data/load_gen
      volumes:
      - name: load-gen-data
        persistentVolumeClaim:
          claimName: load-gen-pvc