apiVersion: v1
kind: Secret
metadata:
  name: dcs-secret
type: Opaque
data:
  RMQ_USER: {{ .Values.dcs-secret.RMQ_USER | b64enc }}
  RMQ_PW: {{ .Values.dcs-secret.RMQ_PW | b64enc }}
  MYSQL_USER: {{ .Values.dcs-secret.MYSQL_USER | b64enc }}
  MYSQL_PW: {{ .Values.dcs-secret.MYSQL_PW | b64enc }}
  IBM_MQ_USER: {{ .Values.dcs-secret.IBM_MQ_USER | b64enc }}
  IBM_MQ_PW: {{ .Values.dcs-secret.IBM_MQ_PW | b64enc }}