apiVersion: v1
kind: ConfigMap
metadata:
  name: dcs-config
data:
  PAYLOAD_DIR: {{ .Values.dcs_config.PAYLOAD_DIR }}
  KAFKA_HOST: {{ .Values.dcs_config.KAFKA_HOST }}
  CA_PATH: {{ .Values.dcs_config.CA_PATH }}
  CERT_PATH: {{ .Values.dcs_config.CERT_PATH }}
  KEY_PATH: {{ .Values.dcs_config.KEY_PATH }}
  KAFKA_FLIGHT_TOPIC: {{ .Values.dcs_config.KAFKA_FLIGHT_TOPIC }}
  KAFKA_PASSENGER_TOPIC: {{ .Values.dcs_config.KAFKA_PASSENGER_TOPIC }}
  KAFKA_RTS_PF_CG_ID: {{ .Values.dcs_config.KAFKA_RTS_PF_CG_ID }}
  log_directory: {{ .Values.dcs_config.log_directory }}
  log_level: {{ .Values.dcs_config.log_level }}
  sampled_flights_no: {{ .Values.dcs_config.sampled_flights_no | quote }}
  sampled_passengers_no: {{ .Values.dcs_config.sampled_passengers_no | quote }}
  PASSENGER_DL_INTERVAL: {{ .Values.dcs_config.PASSENGER_DL_INTERVAL | quote }}
  RMQ_HOST: {{ .Values.dcs_config.RMQ_HOST }}
  RMQ_PORT: {{ .Values.dcs_config.RMQ_PORT | quote }}
  RMQ_FLIGHT_QUEUE: {{ .Values.dcs_config.RMQ_FLIGHT_QUEUE }}
  RMQ_PASSENGER_QUEUE: {{ .Values.dcs_config.RMQ_PASSENGER_QUEUE }}
  RMQ_POLL_INT: {{ .Values.dcs_config.RMQ_POLL_INT | quote }}
  MYSQL_HOST: {{ .Values.dcs_config.MYSQL_HOST }}
  MYSQL_PORT: {{ .Values.dcs_config.MYSQL_PORT | quote }}
  MYSQL_DB: {{ .Values.dcs_config.MYSQL_DB }}
  RMQ_SCHED_PF_QUEUE: {{ .Values.dcs_config.RMQ_SCHED_PF_QUEUE }}
  IBM_MQ_HOST: {{ .Values.dcs_config.IBM_MQ_HOST }}
  IBM_MQ_PORT: {{ .Values.dcs_config.IBM_MQ_PORT | quote }}
  IBM_MQ_QUEUE_MANAGER: {{ .Values.dcs_config.IBM_MQ_QUEUE_MANAGER }}
  IBM_MQ_CHANNEL: {{ .Values.dcs_config.IBM_MQ_CHANNEL }}
  IBM_MQ_KEY_REPO: {{ .Values.dcs_config.IBM_MQ_KEY_REPO }}
  RMQ_SCHED_PF_QUEUE: {{ .Values.dcs_config.RMQ_SCHED_PF_QUEUE }}
  IBM_MQ_QUEUE_NAME: {{ .Values.dcs_config.IBM_MQ_QUEUE_NAME }}
  PF_BE_HOST: {{ .Values.dcs_config.PF_BE_HOST }}
  SCHEDULER_INTERVAL: {{ .Values.dcs_config.SCHEDULER_INTERVAL | quote }}
  KAFKA_DATA_LAKE_TOPIC: {{ .Values.dcs_config.KAFKA_DATA_LAKE_TOPIC }}
