apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector-grpc-service
spec:
  selector:
    app: opentelemetry-collector
  ports:
  - name: otlp-grpc
    port: {{ .Values.otel.otlpReceiverPort }}
    targetPort: {{ .Values.otel.otlpReceiverPort }} 