apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dcs-pvc
spec:
  volumeName: dcs-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
