apiVersion: v1
kind: PersistentVolume
metadata:
  name: dcs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /apps/dcs/data
