global:
  image:
    repository: "kicapman1x/data-combo-service"
    pullPolicy: Always
  replicas:
    dcs-stub: 1
    interface: 1
    rts: 1
    service: 1
    token-gen: 1
  env:
    configmap: "dcs-config"
    secret: "dcs-secret"
  volumes:
    name: "dcs-volume"
    pvc: "dcs-pvc"
    mountPath: "/data/dcs"
